// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_adjustments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountAdjustment = `-- name: CreateAccountAdjustment :one
INSERT INTO account_adjustments (id, account_id, user_id, amount, previous_balance, new_balance, reason, adjustment_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, account_id, user_id, amount, previous_balance, new_balance, reason, adjustment_date, created_at
`

type CreateAccountAdjustmentParams struct {
	ID              pgtype.UUID    `json:"id"`
	AccountID       pgtype.UUID    `json:"account_id"`
	UserID          pgtype.UUID    `json:"user_id"`
	Amount          pgtype.Numeric `json:"amount"`
	PreviousBalance pgtype.Numeric `json:"previous_balance"`
	NewBalance      pgtype.Numeric `json:"new_balance"`
	Reason          *string        `json:"reason"`
	AdjustmentDate  pgtype.Date    `json:"adjustment_date"`
}

func (q *Queries) CreateAccountAdjustment(ctx context.Context, arg CreateAccountAdjustmentParams) (AccountAdjustment, error) {
	row := q.db.QueryRow(ctx, createAccountAdjustment,
		arg.ID,
		arg.AccountID,
		arg.UserID,
		arg.Amount,
		arg.PreviousBalance,
		arg.NewBalance,
		arg.Reason,
		arg.AdjustmentDate,
	)
	var i AccountAdjustment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Amount,
		&i.PreviousBalance,
		&i.NewBalance,
		&i.Reason,
		&i.AdjustmentDate,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountAdjustmentByID = `-- name: GetAccountAdjustmentByID :one
SELECT adj.id, adj.account_id, adj.user_id, adj.amount, adj.previous_balance, adj.new_balance, adj.reason, adj.adjustment_date, adj.created_at, a.name AS account_name
FROM account_adjustments adj
JOIN accounts a ON adj.account_id = a.id
WHERE adj.id = $1 AND adj.user_id = $2
`

type GetAccountAdjustmentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAccountAdjustmentByIDRow struct {
	ID              pgtype.UUID      `json:"id"`
	AccountID       pgtype.UUID      `json:"account_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PreviousBalance pgtype.Numeric   `json:"previous_balance"`
	NewBalance      pgtype.Numeric   `json:"new_balance"`
	Reason          *string          `json:"reason"`
	AdjustmentDate  pgtype.Date      `json:"adjustment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AccountName     string           `json:"account_name"`
}

func (q *Queries) GetAccountAdjustmentByID(ctx context.Context, arg GetAccountAdjustmentByIDParams) (GetAccountAdjustmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountAdjustmentByID, arg.ID, arg.UserID)
	var i GetAccountAdjustmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Amount,
		&i.PreviousBalance,
		&i.NewBalance,
		&i.Reason,
		&i.AdjustmentDate,
		&i.CreatedAt,
		&i.AccountName,
	)
	return i, err
}

const getLatestAdjustmentByAccount = `-- name: GetLatestAdjustmentByAccount :one
SELECT id, account_id, user_id, amount, previous_balance, new_balance, reason, adjustment_date, created_at FROM account_adjustments
WHERE account_id = $1 AND user_id = $2
ORDER BY adjustment_date DESC, created_at DESC
LIMIT 1
`

type GetLatestAdjustmentByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetLatestAdjustmentByAccount(ctx context.Context, arg GetLatestAdjustmentByAccountParams) (AccountAdjustment, error) {
	row := q.db.QueryRow(ctx, getLatestAdjustmentByAccount, arg.AccountID, arg.UserID)
	var i AccountAdjustment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.UserID,
		&i.Amount,
		&i.PreviousBalance,
		&i.NewBalance,
		&i.Reason,
		&i.AdjustmentDate,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountAdjustmentsByAccount = `-- name: ListAccountAdjustmentsByAccount :many
SELECT adj.id, adj.account_id, adj.user_id, adj.amount, adj.previous_balance, adj.new_balance, adj.reason, adj.adjustment_date, adj.created_at, a.name AS account_name
FROM account_adjustments adj
JOIN accounts a ON adj.account_id = a.id
WHERE adj.account_id = $1 AND adj.user_id = $2
ORDER BY adj.adjustment_date DESC, adj.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAccountAdjustmentsByAccountParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListAccountAdjustmentsByAccountRow struct {
	ID              pgtype.UUID      `json:"id"`
	AccountID       pgtype.UUID      `json:"account_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PreviousBalance pgtype.Numeric   `json:"previous_balance"`
	NewBalance      pgtype.Numeric   `json:"new_balance"`
	Reason          *string          `json:"reason"`
	AdjustmentDate  pgtype.Date      `json:"adjustment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AccountName     string           `json:"account_name"`
}

func (q *Queries) ListAccountAdjustmentsByAccount(ctx context.Context, arg ListAccountAdjustmentsByAccountParams) ([]ListAccountAdjustmentsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listAccountAdjustmentsByAccount,
		arg.AccountID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountAdjustmentsByAccountRow{}
	for rows.Next() {
		var i ListAccountAdjustmentsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.Amount,
			&i.PreviousBalance,
			&i.NewBalance,
			&i.Reason,
			&i.AdjustmentDate,
			&i.CreatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountAdjustmentsByDateRange = `-- name: ListAccountAdjustmentsByDateRange :many
SELECT adj.id, adj.account_id, adj.user_id, adj.amount, adj.previous_balance, adj.new_balance, adj.reason, adj.adjustment_date, adj.created_at, a.name AS account_name
FROM account_adjustments adj
JOIN accounts a ON adj.account_id = a.id
WHERE adj.user_id = $1
  AND adj.adjustment_date BETWEEN $2 AND $3
ORDER BY adj.adjustment_date DESC
LIMIT $4 OFFSET $5
`

type ListAccountAdjustmentsByDateRangeParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	AdjustmentDate   pgtype.Date `json:"adjustment_date"`
	AdjustmentDate_2 pgtype.Date `json:"adjustment_date_2"`
	Limit            int32       `json:"limit"`
	Offset           int32       `json:"offset"`
}

type ListAccountAdjustmentsByDateRangeRow struct {
	ID              pgtype.UUID      `json:"id"`
	AccountID       pgtype.UUID      `json:"account_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PreviousBalance pgtype.Numeric   `json:"previous_balance"`
	NewBalance      pgtype.Numeric   `json:"new_balance"`
	Reason          *string          `json:"reason"`
	AdjustmentDate  pgtype.Date      `json:"adjustment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AccountName     string           `json:"account_name"`
}

func (q *Queries) ListAccountAdjustmentsByDateRange(ctx context.Context, arg ListAccountAdjustmentsByDateRangeParams) ([]ListAccountAdjustmentsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listAccountAdjustmentsByDateRange,
		arg.UserID,
		arg.AdjustmentDate,
		arg.AdjustmentDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountAdjustmentsByDateRangeRow{}
	for rows.Next() {
		var i ListAccountAdjustmentsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.Amount,
			&i.PreviousBalance,
			&i.NewBalance,
			&i.Reason,
			&i.AdjustmentDate,
			&i.CreatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountAdjustmentsByUser = `-- name: ListAccountAdjustmentsByUser :many
SELECT adj.id, adj.account_id, adj.user_id, adj.amount, adj.previous_balance, adj.new_balance, adj.reason, adj.adjustment_date, adj.created_at, a.name AS account_name
FROM account_adjustments adj
JOIN accounts a ON adj.account_id = a.id
WHERE adj.user_id = $1
ORDER BY adj.adjustment_date DESC, adj.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAccountAdjustmentsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAccountAdjustmentsByUserRow struct {
	ID              pgtype.UUID      `json:"id"`
	AccountID       pgtype.UUID      `json:"account_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PreviousBalance pgtype.Numeric   `json:"previous_balance"`
	NewBalance      pgtype.Numeric   `json:"new_balance"`
	Reason          *string          `json:"reason"`
	AdjustmentDate  pgtype.Date      `json:"adjustment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AccountName     string           `json:"account_name"`
}

func (q *Queries) ListAccountAdjustmentsByUser(ctx context.Context, arg ListAccountAdjustmentsByUserParams) ([]ListAccountAdjustmentsByUserRow, error) {
	rows, err := q.db.Query(ctx, listAccountAdjustmentsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountAdjustmentsByUserRow{}
	for rows.Next() {
		var i ListAccountAdjustmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.UserID,
			&i.Amount,
			&i.PreviousBalance,
			&i.NewBalance,
			&i.Reason,
			&i.AdjustmentDate,
			&i.CreatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
