// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes)
VALUES ($1, $2, $3, $4, $5, $6, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at
`

type CreateAccountParams struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	Name           string         `json:"name"`
	Type           string         `json:"type"`
	CurrencyCode   *string        `json:"currency_code"`
	InitialBalance pgtype.Numeric `json:"initial_balance"`
	IncludeInTotal *bool          `json:"include_in_total"`
	Color          *string        `json:"color"`
	Icon           *string        `json:"icon"`
	Notes          *string        `json:"notes"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.CurrencyCode,
		arg.InitialBalance,
		arg.IncludeInTotal,
		arg.Color,
		arg.Icon,
		arg.Notes,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.IncludeInTotal,
		&i.Color,
		&i.Icon,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAccount = `-- name: DeactivateAccount :exec
UPDATE accounts
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type DeactivateAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeactivateAccount(ctx context.Context, arg DeactivateAccountParams) error {
	_, err := q.db.Exec(ctx, deactivateAccount, arg.ID, arg.UserID)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at FROM accounts
WHERE id = $1 AND user_id = $2
`

type GetAccountByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.IncludeInTotal,
		&i.Color,
		&i.Icon,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByType = `-- name: GetAccountsByType :many
SELECT id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at FROM accounts
WHERE user_id = $1 AND type = $2 AND is_active = true
ORDER BY name
`

type GetAccountsByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) GetAccountsByType(ctx context.Context, arg GetAccountsByTypeParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CurrencyCode,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.IncludeInTotal,
			&i.Color,
			&i.Icon,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalBalanceByUser = `-- name: GetTotalBalanceByUser :one
SELECT COALESCE(SUM(current_balance), 0) AS total_balance
FROM accounts
WHERE user_id = $1 AND is_active = true AND include_in_total = true
`

func (q *Queries) GetTotalBalanceByUser(ctx context.Context, userID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalBalanceByUser, userID)
	var total_balance interface{}
	err := row.Scan(&total_balance)
	return total_balance, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at FROM accounts
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CurrencyCode,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.IncludeInTotal,
			&i.Color,
			&i.Icon,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAccountsByUser = `-- name: ListActiveAccountsByUser :many
SELECT id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at FROM accounts
WHERE user_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListActiveAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listActiveAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CurrencyCode,
			&i.InitialBalance,
			&i.CurrentBalance,
			&i.IncludeInTotal,
			&i.Color,
			&i.Icon,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2,
    type = $3,
    currency_code = $4,
    include_in_total = $5,
    color = $6,
    icon = $7,
    notes = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $9
RETURNING id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at
`

type UpdateAccountParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Type           string      `json:"type"`
	CurrencyCode   *string     `json:"currency_code"`
	IncludeInTotal *bool       `json:"include_in_total"`
	Color          *string     `json:"color"`
	Icon           *string     `json:"icon"`
	Notes          *string     `json:"notes"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.CurrencyCode,
		arg.IncludeInTotal,
		arg.Color,
		arg.Icon,
		arg.Notes,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.IncludeInTotal,
		&i.Color,
		&i.Icon,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET current_balance = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, name, type, currency_code, initial_balance, current_balance, include_in_total, color, icon, notes, is_active, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID             pgtype.UUID    `json:"id"`
	CurrentBalance pgtype.Numeric `json:"current_balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.CurrentBalance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CurrencyCode,
		&i.InitialBalance,
		&i.CurrentBalance,
		&i.IncludeInTotal,
		&i.Color,
		&i.Icon,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
