// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (id, transaction_id, file_name, file_path, file_type, file_size)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, file_name, file_path, file_type, file_size, uploaded_at
`

type CreateAttachmentParams struct {
	ID            pgtype.UUID `json:"id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	FileName      string      `json:"file_name"`
	FilePath      string      `json:"file_path"`
	FileType      *string     `json:"file_type"`
	FileSize      *int32      `json:"file_size"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.TransactionID,
		arg.FileName,
		arg.FilePath,
		arg.FileType,
		arg.FileSize,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.FileName,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments
WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteAttachmentsByTransaction = `-- name: DeleteAttachmentsByTransaction :exec
DELETE FROM attachments
WHERE transaction_id = $1
`

func (q *Queries) DeleteAttachmentsByTransaction(ctx context.Context, transactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByTransaction, transactionID)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, transaction_id, file_name, file_path, file_type, file_size, uploaded_at FROM attachments
WHERE id = $1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.FileName,
		&i.FilePath,
		&i.FileType,
		&i.FileSize,
		&i.UploadedAt,
	)
	return i, err
}

const listAttachmentsByTransaction = `-- name: ListAttachmentsByTransaction :many
SELECT id, transaction_id, file_name, file_path, file_type, file_size, uploaded_at FROM attachments
WHERE transaction_id = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListAttachmentsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.FileName,
			&i.FilePath,
			&i.FileType,
			&i.FileSize,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
