// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (id, user_id, category_id, name, amount, period, start_date, end_date, alert_threshold)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, category_id, name, amount, period, start_date, end_date, alert_threshold, is_active, created_at, updated_at
`

type CreateBudgetParams struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	CategoryID     pgtype.UUID    `json:"category_id"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Period         string         `json:"period"`
	StartDate      pgtype.Date    `json:"start_date"`
	EndDate        pgtype.Date    `json:"end_date"`
	AlertThreshold pgtype.Numeric `json:"alert_threshold"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.Name,
		arg.Amount,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBudget = `-- name: DeactivateBudget :exec
UPDATE budgets
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type DeactivateBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeactivateBudget(ctx context.Context, arg DeactivateBudgetParams) error {
	_, err := q.db.Exec(ctx, deactivateBudget, arg.ID, arg.UserID)
	return err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.Exec(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at, c.name AS category_name, c.color, c.icon
FROM budgets b
JOIN categories c ON b.category_id = c.id
WHERE b.id = $1 AND b.user_id = $2
`

type GetBudgetByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetBudgetByIDRow struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	CategoryID     pgtype.UUID      `json:"category_id"`
	Name           string           `json:"name"`
	Amount         pgtype.Numeric   `json:"amount"`
	Period         string           `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Numeric   `json:"alert_threshold"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CategoryName   string           `json:"category_name"`
	Color          *string          `json:"color"`
	Icon           *string          `json:"icon"`
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (GetBudgetByIDRow, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, arg.ID, arg.UserID)
	var i GetBudgetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.Color,
		&i.Icon,
	)
	return i, err
}

const getBudgetWithSpending = `-- name: GetBudgetWithSpending :one
SELECT
    b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at,
    c.name AS category_name,
    c.color,
    c.icon,
    COALESCE(SUM(t.amount), 0) AS spent_amount,
    b.amount - COALESCE(SUM(t.amount), 0) AS remaining_amount,
    CASE WHEN b.amount > 0
        THEN ROUND((COALESCE(SUM(t.amount), 0) / b.amount) * 100, 2)
        ELSE 0
    END AS spent_percentage
FROM budgets b
JOIN categories c ON b.category_id = c.id
LEFT JOIN transactions t ON t.category_id = b.category_id
    AND t.user_id = b.user_id
    AND t.type = 'expense'
    AND t.transaction_date BETWEEN $2 AND $3
WHERE b.id = $1 AND b.user_id = $4
GROUP BY b.id, c.name, c.color, c.icon
`

type GetBudgetWithSpendingParams struct {
	ID                pgtype.UUID `json:"id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	UserID            pgtype.UUID `json:"user_id"`
}

type GetBudgetWithSpendingRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Name            string           `json:"name"`
	Amount          pgtype.Numeric   `json:"amount"`
	Period          string           `json:"period"`
	StartDate       pgtype.Date      `json:"start_date"`
	EndDate         pgtype.Date      `json:"end_date"`
	AlertThreshold  pgtype.Numeric   `json:"alert_threshold"`
	IsActive        *bool            `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    string           `json:"category_name"`
	Color           *string          `json:"color"`
	Icon            *string          `json:"icon"`
	SpentAmount     interface{}      `json:"spent_amount"`
	RemainingAmount int32            `json:"remaining_amount"`
	SpentPercentage int32            `json:"spent_percentage"`
}

func (q *Queries) GetBudgetWithSpending(ctx context.Context, arg GetBudgetWithSpendingParams) (GetBudgetWithSpendingRow, error) {
	row := q.db.QueryRow(ctx, getBudgetWithSpending,
		arg.ID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.UserID,
	)
	var i GetBudgetWithSpendingRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.Color,
		&i.Icon,
		&i.SpentAmount,
		&i.RemainingAmount,
		&i.SpentPercentage,
	)
	return i, err
}

const listActiveBudgetsByUser = `-- name: ListActiveBudgetsByUser :many
SELECT b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at, c.name AS category_name, c.color, c.icon
FROM budgets b
JOIN categories c ON b.category_id = c.id
WHERE b.user_id = $1
  AND b.is_active = true
  AND (b.end_date IS NULL OR b.end_date >= CURRENT_DATE)
ORDER BY b.name
`

type ListActiveBudgetsByUserRow struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	CategoryID     pgtype.UUID      `json:"category_id"`
	Name           string           `json:"name"`
	Amount         pgtype.Numeric   `json:"amount"`
	Period         string           `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Numeric   `json:"alert_threshold"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CategoryName   string           `json:"category_name"`
	Color          *string          `json:"color"`
	Icon           *string          `json:"icon"`
}

func (q *Queries) ListActiveBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveBudgetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBudgetsByUserRow{}
	for rows.Next() {
		var i ListActiveBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.Color,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBudgetsExceedingThreshold = `-- name: ListAllBudgetsExceedingThreshold :many
SELECT
    b.id,
    b.user_id,
    b.name,
    b.amount,
    b.alert_threshold,
    COALESCE(SUM(t.amount), 0) AS spent_amount,
    CASE WHEN b.amount > 0
        THEN ROUND((COALESCE(SUM(t.amount), 0) / b.amount) * 100, 2)
        ELSE 0
    END AS spent_percentage
FROM budgets b
LEFT JOIN transactions t ON t.category_id = b.category_id
    AND t.user_id = b.user_id
    AND t.type = 'expense'
    AND t.transaction_date BETWEEN $1 AND $2
WHERE b.is_active = true
  AND (b.end_date IS NULL OR b.end_date >= CURRENT_DATE)
GROUP BY b.id
HAVING CASE WHEN b.amount > 0
    THEN (COALESCE(SUM(t.amount), 0) / b.amount) * 100
    ELSE 0
END >= b.alert_threshold
ORDER BY spent_percentage DESC
`

type ListAllBudgetsExceedingThresholdParams struct {
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type ListAllBudgetsExceedingThresholdRow struct {
	ID              pgtype.UUID    `json:"id"`
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	Amount          pgtype.Numeric `json:"amount"`
	AlertThreshold  pgtype.Numeric `json:"alert_threshold"`
	SpentAmount     interface{}    `json:"spent_amount"`
	SpentPercentage int32          `json:"spent_percentage"`
}

func (q *Queries) ListAllBudgetsExceedingThreshold(ctx context.Context, arg ListAllBudgetsExceedingThresholdParams) ([]ListAllBudgetsExceedingThresholdRow, error) {
	rows, err := q.db.Query(ctx, listAllBudgetsExceedingThreshold, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBudgetsExceedingThresholdRow{}
	for rows.Next() {
		var i ListAllBudgetsExceedingThresholdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.AlertThreshold,
			&i.SpentAmount,
			&i.SpentPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at, c.name AS category_name, c.color, c.icon
FROM budgets b
JOIN categories c ON b.category_id = c.id
WHERE b.user_id = $1
ORDER BY b.name
`

type ListBudgetsByUserRow struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	CategoryID     pgtype.UUID      `json:"category_id"`
	Name           string           `json:"name"`
	Amount         pgtype.Numeric   `json:"amount"`
	Period         string           `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Numeric   `json:"alert_threshold"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	CategoryName   string           `json:"category_name"`
	Color          *string          `json:"color"`
	Icon           *string          `json:"icon"`
}

func (q *Queries) ListBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListBudgetsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsByUserRow{}
	for rows.Next() {
		var i ListBudgetsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.Color,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsExceedingThreshold = `-- name: ListBudgetsExceedingThreshold :many
SELECT
    b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at,
    c.name AS category_name,
    COALESCE(SUM(t.amount), 0) AS spent_amount,
    CASE WHEN b.amount > 0
        THEN ROUND((COALESCE(SUM(t.amount), 0) / b.amount) * 100, 2)
        ELSE 0
    END AS spent_percentage
FROM budgets b
JOIN categories c ON b.category_id = c.id
LEFT JOIN transactions t ON t.category_id = b.category_id
    AND t.user_id = b.user_id
    AND t.type = 'expense'
    AND t.transaction_date BETWEEN $2 AND $3
WHERE b.user_id = $1 AND b.is_active = true
GROUP BY b.id, c.name
HAVING CASE WHEN b.amount > 0
    THEN (COALESCE(SUM(t.amount), 0) / b.amount) * 100
    ELSE 0
END >= b.alert_threshold
`

type ListBudgetsExceedingThresholdParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type ListBudgetsExceedingThresholdRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Name            string           `json:"name"`
	Amount          pgtype.Numeric   `json:"amount"`
	Period          string           `json:"period"`
	StartDate       pgtype.Date      `json:"start_date"`
	EndDate         pgtype.Date      `json:"end_date"`
	AlertThreshold  pgtype.Numeric   `json:"alert_threshold"`
	IsActive        *bool            `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    string           `json:"category_name"`
	SpentAmount     interface{}      `json:"spent_amount"`
	SpentPercentage int32            `json:"spent_percentage"`
}

func (q *Queries) ListBudgetsExceedingThreshold(ctx context.Context, arg ListBudgetsExceedingThresholdParams) ([]ListBudgetsExceedingThresholdRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsExceedingThreshold, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsExceedingThresholdRow{}
	for rows.Next() {
		var i ListBudgetsExceedingThresholdRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.SpentAmount,
			&i.SpentPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsWithSpending = `-- name: ListBudgetsWithSpending :many
SELECT
    b.id, b.user_id, b.category_id, b.name, b.amount, b.period, b.start_date, b.end_date, b.alert_threshold, b.is_active, b.created_at, b.updated_at,
    c.name AS category_name,
    c.color,
    c.icon,
    COALESCE(SUM(t.amount), 0) AS spent_amount,
    b.amount - COALESCE(SUM(t.amount), 0) AS remaining_amount,
    CASE WHEN b.amount > 0
        THEN ROUND((COALESCE(SUM(t.amount), 0) / b.amount) * 100, 2)
        ELSE 0
    END AS spent_percentage
FROM budgets b
JOIN categories c ON b.category_id = c.id
LEFT JOIN transactions t ON t.category_id = b.category_id
    AND t.user_id = b.user_id
    AND t.type = 'expense'
    AND t.transaction_date BETWEEN $2 AND $3
WHERE b.user_id = $1 AND b.is_active = true
GROUP BY b.id, c.name, c.color, c.icon
ORDER BY spent_percentage DESC
`

type ListBudgetsWithSpendingParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type ListBudgetsWithSpendingRow struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	CategoryID      pgtype.UUID      `json:"category_id"`
	Name            string           `json:"name"`
	Amount          pgtype.Numeric   `json:"amount"`
	Period          string           `json:"period"`
	StartDate       pgtype.Date      `json:"start_date"`
	EndDate         pgtype.Date      `json:"end_date"`
	AlertThreshold  pgtype.Numeric   `json:"alert_threshold"`
	IsActive        *bool            `json:"is_active"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	CategoryName    string           `json:"category_name"`
	Color           *string          `json:"color"`
	Icon            *string          `json:"icon"`
	SpentAmount     interface{}      `json:"spent_amount"`
	RemainingAmount int32            `json:"remaining_amount"`
	SpentPercentage int32            `json:"spent_percentage"`
}

func (q *Queries) ListBudgetsWithSpending(ctx context.Context, arg ListBudgetsWithSpendingParams) ([]ListBudgetsWithSpendingRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsWithSpending, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsWithSpendingRow{}
	for rows.Next() {
		var i ListBudgetsWithSpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.Color,
			&i.Icon,
			&i.SpentAmount,
			&i.RemainingAmount,
			&i.SpentPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET name = $2,
    amount = $3,
    period = $4,
    start_date = $5,
    end_date = $6,
    alert_threshold = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $8
RETURNING id, user_id, category_id, name, amount, period, start_date, end_date, alert_threshold, is_active, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Period         string         `json:"period"`
	StartDate      pgtype.Date    `json:"start_date"`
	EndDate        pgtype.Date    `json:"end_date"`
	AlertThreshold pgtype.Numeric `json:"alert_threshold"`
	UserID         pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
		arg.UserID,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Name,
		&i.Amount,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
