// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, user_id, name, type, color, icon, parent_category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at
`

type CreateCategoryParams struct {
	ID               pgtype.UUID `json:"id"`
	UserID           pgtype.UUID `json:"user_id"`
	Name             string      `json:"name"`
	Type             string      `json:"type"`
	Color            *string     `json:"color"`
	Icon             *string     `json:"icon"`
	ParentCategoryID pgtype.UUID `json:"parent_category_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Icon,
		arg.ParentCategoryID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.ParentCategoryID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.ParentCategoryID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByIDAndUser = `-- name: GetCategoryByIDAndUser :one
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE id = $1 AND user_id = $2
`

type GetCategoryByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetCategoryByIDAndUser(ctx context.Context, arg GetCategoryByIDAndUserParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByIDAndUser, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.ParentCategoryID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByType = `-- name: ListCategoriesByType :many
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE (user_id = $1 OR is_system = true) AND type = $2
ORDER BY name
`

type ListCategoriesByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.ParentCategoryID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByUser = `-- name: ListCategoriesByUser :many
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE user_id = $1 OR is_system = true
ORDER BY type, name
`

func (q *Queries) ListCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.ParentCategoryID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubcategories = `-- name: ListSubcategories :many
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE parent_category_id = $1
ORDER BY name
`

func (q *Queries) ListSubcategories(ctx context.Context, parentCategoryID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSubcategories, parentCategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.ParentCategoryID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemCategories = `-- name: ListSystemCategories :many
SELECT id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at FROM categories
WHERE is_system = true
ORDER BY type, name
`

func (q *Queries) ListSystemCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSystemCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Icon,
			&i.ParentCategoryID,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSystemCategory = `-- name: SetSystemCategory :exec
UPDATE categories
SET is_system = true
WHERE id = $1 AND user_id = $2
`

type SetSystemCategoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetSystemCategory(ctx context.Context, arg SetSystemCategoryParams) error {
	_, err := q.db.Exec(ctx, setSystemCategory, arg.ID, arg.UserID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    color = $3,
    icon = $4,
    parent_category_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $6
RETURNING id, user_id, name, type, color, icon, parent_category_id, is_system, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Color            *string     `json:"color"`
	Icon             *string     `json:"icon"`
	ParentCategoryID pgtype.UUID `json:"parent_category_id"`
	UserID           pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Icon,
		arg.ParentCategoryID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Icon,
		&i.ParentCategoryID,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
