// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeGoal = `-- name: CompleteGoal :one
UPDATE goals
SET is_completed = true,
    completed_date = CURRENT_DATE,
    current_amount = target_amount,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, account_id, name, description, target_amount, current_amount, currency_code, target_date, goal_type, is_completed, completed_date, created_at, updated_at
`

type CompleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CompleteGoal(ctx context.Context, arg CompleteGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, completeGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.CurrencyCode,
		&i.TargetDate,
		&i.GoalType,
		&i.IsCompleted,
		&i.CompletedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (id, user_id, account_id, name, description, target_amount, currency_code, target_date, goal_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, account_id, name, description, target_amount, current_amount, currency_code, target_date, goal_type, is_completed, completed_date, created_at, updated_at
`

type CreateGoalParams struct {
	ID           pgtype.UUID    `json:"id"`
	UserID       pgtype.UUID    `json:"user_id"`
	AccountID    pgtype.UUID    `json:"account_id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	CurrencyCode *string        `json:"currency_code"`
	TargetDate   pgtype.Date    `json:"target_date"`
	GoalType     string         `json:"goal_type"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.TargetAmount,
		arg.CurrencyCode,
		arg.TargetDate,
		arg.GoalType,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.CurrencyCode,
		&i.TargetDate,
		&i.GoalType,
		&i.IsCompleted,
		&i.CompletedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT g.id, g.user_id, g.account_id, g.name, g.description, g.target_amount, g.current_amount, g.currency_code, g.target_date, g.goal_type, g.is_completed, g.completed_date, g.created_at, g.updated_at, a.name AS account_name
FROM goals g
LEFT JOIN accounts a ON g.account_id = a.id
WHERE g.id = $1 AND g.user_id = $2
`

type GetGoalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetGoalByIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AccountID     pgtype.UUID      `json:"account_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	TargetAmount  pgtype.Numeric   `json:"target_amount"`
	CurrentAmount pgtype.Numeric   `json:"current_amount"`
	CurrencyCode  *string          `json:"currency_code"`
	TargetDate    pgtype.Date      `json:"target_date"`
	GoalType      string           `json:"goal_type"`
	IsCompleted   *bool            `json:"is_completed"`
	CompletedDate pgtype.Date      `json:"completed_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	AccountName   *string          `json:"account_name"`
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (GetGoalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoalByID, arg.ID, arg.UserID)
	var i GetGoalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.CurrencyCode,
		&i.TargetDate,
		&i.GoalType,
		&i.IsCompleted,
		&i.CompletedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountName,
	)
	return i, err
}

const getGoalProgress = `-- name: GetGoalProgress :one
SELECT
    id,
    name,
    target_amount,
    current_amount,
    CASE WHEN target_amount > 0
        THEN ROUND((current_amount / target_amount) * 100, 2)
        ELSE 0
    END AS progress_percentage,
    target_amount - current_amount AS remaining_amount,
    target_date,
    is_completed
FROM goals
WHERE id = $1 AND user_id = $2
`

type GetGoalProgressParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetGoalProgressRow struct {
	ID                 pgtype.UUID    `json:"id"`
	Name               string         `json:"name"`
	TargetAmount       pgtype.Numeric `json:"target_amount"`
	CurrentAmount      pgtype.Numeric `json:"current_amount"`
	ProgressPercentage int32          `json:"progress_percentage"`
	RemainingAmount    int32          `json:"remaining_amount"`
	TargetDate         pgtype.Date    `json:"target_date"`
	IsCompleted        *bool          `json:"is_completed"`
}

func (q *Queries) GetGoalProgress(ctx context.Context, arg GetGoalProgressParams) (GetGoalProgressRow, error) {
	row := q.db.QueryRow(ctx, getGoalProgress, arg.ID, arg.UserID)
	var i GetGoalProgressRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.ProgressPercentage,
		&i.RemainingAmount,
		&i.TargetDate,
		&i.IsCompleted,
	)
	return i, err
}

const listActiveGoalsByUser = `-- name: ListActiveGoalsByUser :many
SELECT g.id, g.user_id, g.account_id, g.name, g.description, g.target_amount, g.current_amount, g.currency_code, g.target_date, g.goal_type, g.is_completed, g.completed_date, g.created_at, g.updated_at, a.name AS account_name
FROM goals g
LEFT JOIN accounts a ON g.account_id = a.id
WHERE g.user_id = $1 AND g.is_completed = false
ORDER BY g.target_date ASC NULLS LAST
`

type ListActiveGoalsByUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AccountID     pgtype.UUID      `json:"account_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	TargetAmount  pgtype.Numeric   `json:"target_amount"`
	CurrentAmount pgtype.Numeric   `json:"current_amount"`
	CurrencyCode  *string          `json:"currency_code"`
	TargetDate    pgtype.Date      `json:"target_date"`
	GoalType      string           `json:"goal_type"`
	IsCompleted   *bool            `json:"is_completed"`
	CompletedDate pgtype.Date      `json:"completed_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	AccountName   *string          `json:"account_name"`
}

func (q *Queries) ListActiveGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveGoalsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveGoalsByUserRow{}
	for rows.Next() {
		var i ListActiveGoalsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.CurrencyCode,
			&i.TargetDate,
			&i.GoalType,
			&i.IsCompleted,
			&i.CompletedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByType = `-- name: ListGoalsByType :many
SELECT g.id, g.user_id, g.account_id, g.name, g.description, g.target_amount, g.current_amount, g.currency_code, g.target_date, g.goal_type, g.is_completed, g.completed_date, g.created_at, g.updated_at, a.name AS account_name
FROM goals g
LEFT JOIN accounts a ON g.account_id = a.id
WHERE g.user_id = $1 AND g.goal_type = $2
ORDER BY g.target_date ASC NULLS LAST
`

type ListGoalsByTypeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	GoalType string      `json:"goal_type"`
}

type ListGoalsByTypeRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AccountID     pgtype.UUID      `json:"account_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	TargetAmount  pgtype.Numeric   `json:"target_amount"`
	CurrentAmount pgtype.Numeric   `json:"current_amount"`
	CurrencyCode  *string          `json:"currency_code"`
	TargetDate    pgtype.Date      `json:"target_date"`
	GoalType      string           `json:"goal_type"`
	IsCompleted   *bool            `json:"is_completed"`
	CompletedDate pgtype.Date      `json:"completed_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	AccountName   *string          `json:"account_name"`
}

func (q *Queries) ListGoalsByType(ctx context.Context, arg ListGoalsByTypeParams) ([]ListGoalsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByType, arg.UserID, arg.GoalType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsByTypeRow{}
	for rows.Next() {
		var i ListGoalsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.CurrencyCode,
			&i.TargetDate,
			&i.GoalType,
			&i.IsCompleted,
			&i.CompletedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByUser = `-- name: ListGoalsByUser :many
SELECT g.id, g.user_id, g.account_id, g.name, g.description, g.target_amount, g.current_amount, g.currency_code, g.target_date, g.goal_type, g.is_completed, g.completed_date, g.created_at, g.updated_at, a.name AS account_name
FROM goals g
LEFT JOIN accounts a ON g.account_id = a.id
WHERE g.user_id = $1
ORDER BY g.target_date ASC NULLS LAST, g.created_at DESC
`

type ListGoalsByUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AccountID     pgtype.UUID      `json:"account_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	TargetAmount  pgtype.Numeric   `json:"target_amount"`
	CurrentAmount pgtype.Numeric   `json:"current_amount"`
	CurrencyCode  *string          `json:"currency_code"`
	TargetDate    pgtype.Date      `json:"target_date"`
	GoalType      string           `json:"goal_type"`
	IsCompleted   *bool            `json:"is_completed"`
	CompletedDate pgtype.Date      `json:"completed_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	AccountName   *string          `json:"account_name"`
}

func (q *Queries) ListGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]ListGoalsByUserRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsByUserRow{}
	for rows.Next() {
		var i ListGoalsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.TargetAmount,
			&i.CurrentAmount,
			&i.CurrencyCode,
			&i.TargetDate,
			&i.GoalType,
			&i.IsCompleted,
			&i.CompletedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsReachedTarget = `-- name: ListGoalsReachedTarget :many
SELECT id, user_id, name, target_amount, current_amount
FROM goals
WHERE is_completed = false
  AND current_amount >= target_amount
`

type ListGoalsReachedTargetRow struct {
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
	Name          string         `json:"name"`
	TargetAmount  pgtype.Numeric `json:"target_amount"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
}

func (q *Queries) ListGoalsReachedTarget(ctx context.Context) ([]ListGoalsReachedTargetRow, error) {
	rows, err := q.db.Query(ctx, listGoalsReachedTarget)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsReachedTargetRow{}
	for rows.Next() {
		var i ListGoalsReachedTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TargetAmount,
			&i.CurrentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET name = $2,
    description = $3,
    target_amount = $4,
    target_date = $5,
    goal_type = $6,
    account_id = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $8
RETURNING id, user_id, account_id, name, description, target_amount, current_amount, currency_code, target_date, goal_type, is_completed, completed_date, created_at, updated_at
`

type UpdateGoalParams struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	TargetAmount pgtype.Numeric `json:"target_amount"`
	TargetDate   pgtype.Date    `json:"target_date"`
	GoalType     string         `json:"goal_type"`
	AccountID    pgtype.UUID    `json:"account_id"`
	UserID       pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TargetAmount,
		arg.TargetDate,
		arg.GoalType,
		arg.AccountID,
		arg.UserID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.CurrencyCode,
		&i.TargetDate,
		&i.GoalType,
		&i.IsCompleted,
		&i.CompletedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoalCurrentAmount = `-- name: UpdateGoalCurrentAmount :one
UPDATE goals
SET current_amount = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, account_id, name, description, target_amount, current_amount, currency_code, target_date, goal_type, is_completed, completed_date, created_at, updated_at
`

type UpdateGoalCurrentAmountParams struct {
	ID            pgtype.UUID    `json:"id"`
	CurrentAmount pgtype.Numeric `json:"current_amount"`
	UserID        pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateGoalCurrentAmount(ctx context.Context, arg UpdateGoalCurrentAmountParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoalCurrentAmount, arg.ID, arg.CurrentAmount, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.TargetAmount,
		&i.CurrentAmount,
		&i.CurrencyCode,
		&i.TargetDate,
		&i.GoalType,
		&i.IsCompleted,
		&i.CompletedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
