// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	Name           string           `json:"name"`
	Type           string           `json:"type"`
	CurrencyCode   *string          `json:"currency_code"`
	InitialBalance pgtype.Numeric   `json:"initial_balance"`
	CurrentBalance pgtype.Numeric   `json:"current_balance"`
	IncludeInTotal *bool            `json:"include_in_total"`
	Color          *string          `json:"color"`
	Icon           *string          `json:"icon"`
	Notes          *string          `json:"notes"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type AccountAdjustment struct {
	ID              pgtype.UUID      `json:"id"`
	AccountID       pgtype.UUID      `json:"account_id"`
	UserID          pgtype.UUID      `json:"user_id"`
	Amount          pgtype.Numeric   `json:"amount"`
	PreviousBalance pgtype.Numeric   `json:"previous_balance"`
	NewBalance      pgtype.Numeric   `json:"new_balance"`
	Reason          *string          `json:"reason"`
	AdjustmentDate  pgtype.Date      `json:"adjustment_date"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Attachment struct {
	ID            pgtype.UUID      `json:"id"`
	TransactionID pgtype.UUID      `json:"transaction_id"`
	FileName      string           `json:"file_name"`
	FilePath      string           `json:"file_path"`
	FileType      *string          `json:"file_type"`
	FileSize      *int32           `json:"file_size"`
	UploadedAt    pgtype.Timestamp `json:"uploaded_at"`
}

type Budget struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	CategoryID     pgtype.UUID      `json:"category_id"`
	Name           string           `json:"name"`
	Amount         pgtype.Numeric   `json:"amount"`
	Period         string           `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Numeric   `json:"alert_threshold"`
	IsActive       *bool            `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type Category struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	Name             string           `json:"name"`
	Type             string           `json:"type"`
	Color            *string          `json:"color"`
	Icon             *string          `json:"icon"`
	ParentCategoryID pgtype.UUID      `json:"parent_category_id"`
	IsSystem         *bool            `json:"is_system"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Goal struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	AccountID     pgtype.UUID      `json:"account_id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	TargetAmount  pgtype.Numeric   `json:"target_amount"`
	CurrentAmount pgtype.Numeric   `json:"current_amount"`
	CurrencyCode  *string          `json:"currency_code"`
	TargetDate    pgtype.Date      `json:"target_date"`
	GoalType      string           `json:"goal_type"`
	IsCompleted   *bool            `json:"is_completed"`
	CompletedDate pgtype.Date      `json:"completed_date"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Notification struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Type        string           `json:"type"`
	Title       string           `json:"title"`
	Message     string           `json:"message"`
	IsRead      *bool            `json:"is_read"`
	RelatedID   pgtype.UUID      `json:"related_id"`
	RelatedType *string          `json:"related_type"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type RecurringTransaction struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Transaction struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	TransferID             pgtype.UUID      `json:"transfer_id"`
}

type Transfer struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	FromAccountID     pgtype.UUID      `json:"from_account_id"`
	ToAccountID       pgtype.UUID      `json:"to_account_id"`
	FromTransactionID pgtype.UUID      `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID      `json:"to_transaction_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	ToAmount          pgtype.Numeric   `json:"to_amount"`
	ExchangeRate      pgtype.Numeric   `json:"exchange_rate"`
	TransferDate      pgtype.Date      `json:"transfer_date"`
	Description       *string          `json:"description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID      `json:"id"`
	FirebaseUid  string           `json:"firebase_uid"`
	CurrencyCode string           `json:"currency_code"`
	IsAdmin      bool             `json:"is_admin"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
