// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteGoal(ctx context.Context, arg CompleteGoalParams) (Goal, error)
	CountTransactionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUser(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountAdjustment(ctx context.Context, arg CreateAccountAdjustmentParams) (AccountAdjustment, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAccount(ctx context.Context, arg DeactivateAccountParams) error
	DeactivateBudget(ctx context.Context, arg DeactivateBudgetParams) error
	DeactivateRecurringTransaction(ctx context.Context, arg DeactivateRecurringTransactionParams) error
	DeleteAttachment(ctx context.Context, id pgtype.UUID) error
	DeleteAttachmentsByTransaction(ctx context.Context, transactionID pgtype.UUID) error
	DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteGoal(ctx context.Context, arg DeleteGoalParams) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteReadNotifications(ctx context.Context, userID pgtype.UUID) error
	DeleteRecurringTransaction(ctx context.Context, arg DeleteRecurringTransactionParams) error
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	DeleteTransfer(ctx context.Context, arg DeleteTransferParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAccountAdjustmentByID(ctx context.Context, arg GetAccountAdjustmentByIDParams) (GetAccountAdjustmentByIDRow, error)
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetAccountsByType(ctx context.Context, arg GetAccountsByTypeParams) ([]Account, error)
	GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error)
	GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (GetBudgetByIDRow, error)
	GetBudgetWithSpending(ctx context.Context, arg GetBudgetWithSpendingParams) (GetBudgetWithSpendingRow, error)
	GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryByIDAndUser(ctx context.Context, arg GetCategoryByIDAndUserParams) (Category, error)
	GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (GetGoalByIDRow, error)
	GetGoalProgress(ctx context.Context, arg GetGoalProgressParams) (GetGoalProgressRow, error)
	GetIncomeVsExpenseByMonth(ctx context.Context, arg GetIncomeVsExpenseByMonthParams) ([]GetIncomeVsExpenseByMonthRow, error)
	GetLatestAdjustmentByAccount(ctx context.Context, accountID pgtype.UUID) (AccountAdjustment, error)
	GetMonthlySpendingByCategory(ctx context.Context, arg GetMonthlySpendingByCategoryParams) ([]GetMonthlySpendingByCategoryRow, error)
	GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error)
	GetRecurringTransactionByID(ctx context.Context, arg GetRecurringTransactionByIDParams) (GetRecurringTransactionByIDRow, error)
	GetTotalBalanceByUser(ctx context.Context, userID pgtype.UUID) (interface{}, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error)
	GetTransactionSummaryByDateRange(ctx context.Context, arg GetTransactionSummaryByDateRangeParams) (GetTransactionSummaryByDateRangeRow, error)
	GetTransferByID(ctx context.Context, arg GetTransferByIDParams) (GetTransferByIDRow, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAccountAdjustmentsByAccount(ctx context.Context, arg ListAccountAdjustmentsByAccountParams) ([]ListAccountAdjustmentsByAccountRow, error)
	ListAccountAdjustmentsByDateRange(ctx context.Context, arg ListAccountAdjustmentsByDateRangeParams) ([]ListAccountAdjustmentsByDateRangeRow, error)
	ListAccountAdjustmentsByUser(ctx context.Context, arg ListAccountAdjustmentsByUserParams) ([]ListAccountAdjustmentsByUserRow, error)
	ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	ListActiveAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error)
	ListActiveBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveBudgetsByUserRow, error)
	ListActiveGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveGoalsByUserRow, error)
	ListActiveRecurringTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveRecurringTransactionsByUserRow, error)
	ListAttachmentsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Attachment, error)
	ListAutoCreateDueRecurringTransactions(ctx context.Context, nextDueDate pgtype.Date) ([]ListAutoCreateDueRecurringTransactionsRow, error)
	ListBudgetsByUser(ctx context.Context, userID pgtype.UUID) ([]ListBudgetsByUserRow, error)
	ListBudgetsExceedingThreshold(ctx context.Context, arg ListBudgetsExceedingThresholdParams) ([]ListBudgetsExceedingThresholdRow, error)
	ListBudgetsWithSpending(ctx context.Context, arg ListBudgetsWithSpendingParams) ([]ListBudgetsWithSpendingRow, error)
	ListCategoriesByType(ctx context.Context, arg ListCategoriesByTypeParams) ([]Category, error)
	ListCategoriesByUser(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	ListDueRecurringTransactions(ctx context.Context, nextDueDate pgtype.Date) ([]ListDueRecurringTransactionsRow, error)
	ListGoalsByType(ctx context.Context, arg ListGoalsByTypeParams) ([]ListGoalsByTypeRow, error)
	ListGoalsByUser(ctx context.Context, userID pgtype.UUID) ([]ListGoalsByUserRow, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListRecurringTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListRecurringTransactionsByUserRow, error)
	ListSubcategories(ctx context.Context, parentCategoryID pgtype.UUID) ([]Category, error)
	ListSystemCategories(ctx context.Context) ([]Category, error)
	ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error)
	ListTransactionsByCategory(ctx context.Context, arg ListTransactionsByCategoryParams) ([]ListTransactionsByCategoryRow, error)
	ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]ListTransactionsByDateRangeRow, error)
	ListTransactionsByTag(ctx context.Context, arg ListTransactionsByTagParams) ([]ListTransactionsByTagRow, error)
	ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]ListTransactionsByTypeRow, error)
	ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error)
	ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]ListTransfersByAccountRow, error)
	ListTransfersByDateRange(ctx context.Context, arg ListTransfersByDateRangeParams) ([]ListTransfersByDateRangeRow, error)
	ListTransfersByUser(ctx context.Context, arg ListTransfersByUserParams) ([]ListTransfersByUserRow, error)
	ListUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
	ListUser(ctx context.Context) ([]User, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	SetSystemCategory(ctx context.Context, arg SetSystemCategoryParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateGoalCurrentAmount(ctx context.Context, arg UpdateGoalCurrentAmountParams) (Goal, error)
	UpdateNextDueDate(ctx context.Context, arg UpdateNextDueDateParams) (RecurringTransaction, error)
	UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserCurrency(ctx context.Context, arg UpdateUserCurrencyParams) error
}

var _ Querier = (*Queries)(nil)
