// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringTransaction = `-- name: CreateRecurringTransaction :one
INSERT INTO recurring_transactions (
    id, user_id, account_id, category_id, type,
    amount, currency_code, description, frequency,
    start_date, end_date, next_due_date, auto_create
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, account_id, category_id, type, amount, currency_code, description, frequency, start_date, end_date, next_due_date, last_processed_date, is_active, auto_create, created_at, updated_at
`

type CreateRecurringTransactionParams struct {
	ID           pgtype.UUID    `json:"id"`
	UserID       pgtype.UUID    `json:"user_id"`
	AccountID    pgtype.UUID    `json:"account_id"`
	CategoryID   pgtype.UUID    `json:"category_id"`
	Type         string         `json:"type"`
	Amount       pgtype.Numeric `json:"amount"`
	CurrencyCode *string        `json:"currency_code"`
	Description  string         `json:"description"`
	Frequency    string         `json:"frequency"`
	StartDate    pgtype.Date    `json:"start_date"`
	EndDate      pgtype.Date    `json:"end_date"`
	NextDueDate  pgtype.Date    `json:"next_due_date"`
	AutoCreate   *bool          `json:"auto_create"`
}

func (q *Queries) CreateRecurringTransaction(ctx context.Context, arg CreateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, createRecurringTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.CurrencyCode,
		arg.Description,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.NextDueDate,
		arg.AutoCreate,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.NextDueDate,
		&i.LastProcessedDate,
		&i.IsActive,
		&i.AutoCreate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateRecurringTransaction = `-- name: DeactivateRecurringTransaction :exec
UPDATE recurring_transactions
SET is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type DeactivateRecurringTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeactivateRecurringTransaction(ctx context.Context, arg DeactivateRecurringTransactionParams) error {
	_, err := q.db.Exec(ctx, deactivateRecurringTransaction, arg.ID, arg.UserID)
	return err
}

const deleteRecurringTransaction = `-- name: DeleteRecurringTransaction :exec
DELETE FROM recurring_transactions
WHERE id = $1 AND user_id = $2
`

type DeleteRecurringTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteRecurringTransaction(ctx context.Context, arg DeleteRecurringTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteRecurringTransaction, arg.ID, arg.UserID)
	return err
}

const getRecurringTransactionByID = `-- name: GetRecurringTransactionByID :one
SELECT r.id, r.user_id, r.account_id, r.category_id, r.type, r.amount, r.currency_code, r.description, r.frequency, r.start_date, r.end_date, r.next_due_date, r.last_processed_date, r.is_active, r.auto_create, r.created_at, r.updated_at, c.name AS category_name, a.name AS account_name
FROM recurring_transactions r
LEFT JOIN categories c ON r.category_id = c.id
LEFT JOIN accounts a ON r.account_id = a.id
WHERE r.id = $1 AND r.user_id = $2
`

type GetRecurringTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetRecurringTransactionByIDRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CategoryName      *string          `json:"category_name"`
	AccountName       *string          `json:"account_name"`
}

func (q *Queries) GetRecurringTransactionByID(ctx context.Context, arg GetRecurringTransactionByIDParams) (GetRecurringTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getRecurringTransactionByID, arg.ID, arg.UserID)
	var i GetRecurringTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.NextDueDate,
		&i.LastProcessedDate,
		&i.IsActive,
		&i.AutoCreate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.AccountName,
	)
	return i, err
}

const listActiveRecurringTransactionsByUser = `-- name: ListActiveRecurringTransactionsByUser :many
SELECT r.id, r.user_id, r.account_id, r.category_id, r.type, r.amount, r.currency_code, r.description, r.frequency, r.start_date, r.end_date, r.next_due_date, r.last_processed_date, r.is_active, r.auto_create, r.created_at, r.updated_at, c.name AS category_name, a.name AS account_name
FROM recurring_transactions r
LEFT JOIN categories c ON r.category_id = c.id
LEFT JOIN accounts a ON r.account_id = a.id
WHERE r.user_id = $1
  AND r.is_active = true
  AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE)
ORDER BY r.next_due_date ASC
`

type ListActiveRecurringTransactionsByUserRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CategoryName      *string          `json:"category_name"`
	AccountName       *string          `json:"account_name"`
}

func (q *Queries) ListActiveRecurringTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListActiveRecurringTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRecurringTransactionsByUserRow{}
	for rows.Next() {
		var i ListActiveRecurringTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.NextDueDate,
			&i.LastProcessedDate,
			&i.IsActive,
			&i.AutoCreate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoCreateDueRecurringTransactions = `-- name: ListAutoCreateDueRecurringTransactions :many
SELECT r.id, r.user_id, r.account_id, r.category_id, r.type, r.amount, r.currency_code, r.description, r.frequency, r.start_date, r.end_date, r.next_due_date, r.last_processed_date, r.is_active, r.auto_create, r.created_at, r.updated_at, c.name AS category_name, a.name AS account_name
FROM recurring_transactions r
LEFT JOIN categories c ON r.category_id = c.id
LEFT JOIN accounts a ON r.account_id = a.id
WHERE r.is_active = true
  AND r.auto_create = true
  AND r.next_due_date <= $1
  AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE)
ORDER BY r.next_due_date ASC
`

type ListAutoCreateDueRecurringTransactionsRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CategoryName      *string          `json:"category_name"`
	AccountName       *string          `json:"account_name"`
}

func (q *Queries) ListAutoCreateDueRecurringTransactions(ctx context.Context, nextDueDate pgtype.Date) ([]ListAutoCreateDueRecurringTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listAutoCreateDueRecurringTransactions, nextDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutoCreateDueRecurringTransactionsRow{}
	for rows.Next() {
		var i ListAutoCreateDueRecurringTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.NextDueDate,
			&i.LastProcessedDate,
			&i.IsActive,
			&i.AutoCreate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueRecurringTransactions = `-- name: ListDueRecurringTransactions :many
SELECT r.id, r.user_id, r.account_id, r.category_id, r.type, r.amount, r.currency_code, r.description, r.frequency, r.start_date, r.end_date, r.next_due_date, r.last_processed_date, r.is_active, r.auto_create, r.created_at, r.updated_at, c.name AS category_name, a.name AS account_name
FROM recurring_transactions r
LEFT JOIN categories c ON r.category_id = c.id
LEFT JOIN accounts a ON r.account_id = a.id
WHERE r.is_active = true
  AND r.next_due_date <= $1
  AND (r.end_date IS NULL OR r.end_date >= CURRENT_DATE)
ORDER BY r.next_due_date ASC
`

type ListDueRecurringTransactionsRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CategoryName      *string          `json:"category_name"`
	AccountName       *string          `json:"account_name"`
}

func (q *Queries) ListDueRecurringTransactions(ctx context.Context, nextDueDate pgtype.Date) ([]ListDueRecurringTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listDueRecurringTransactions, nextDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueRecurringTransactionsRow{}
	for rows.Next() {
		var i ListDueRecurringTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.NextDueDate,
			&i.LastProcessedDate,
			&i.IsActive,
			&i.AutoCreate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTransactionsByUser = `-- name: ListRecurringTransactionsByUser :many
SELECT r.id, r.user_id, r.account_id, r.category_id, r.type, r.amount, r.currency_code, r.description, r.frequency, r.start_date, r.end_date, r.next_due_date, r.last_processed_date, r.is_active, r.auto_create, r.created_at, r.updated_at, c.name AS category_name, a.name AS account_name
FROM recurring_transactions r
LEFT JOIN categories c ON r.category_id = c.id
LEFT JOIN accounts a ON r.account_id = a.id
WHERE r.user_id = $1
ORDER BY r.next_due_date ASC
`

type ListRecurringTransactionsByUserRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	AccountID         pgtype.UUID      `json:"account_id"`
	CategoryID        pgtype.UUID      `json:"category_id"`
	Type              string           `json:"type"`
	Amount            pgtype.Numeric   `json:"amount"`
	CurrencyCode      *string          `json:"currency_code"`
	Description       string           `json:"description"`
	Frequency         string           `json:"frequency"`
	StartDate         pgtype.Date      `json:"start_date"`
	EndDate           pgtype.Date      `json:"end_date"`
	NextDueDate       pgtype.Date      `json:"next_due_date"`
	LastProcessedDate pgtype.Date      `json:"last_processed_date"`
	IsActive          *bool            `json:"is_active"`
	AutoCreate        *bool            `json:"auto_create"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	CategoryName      *string          `json:"category_name"`
	AccountName       *string          `json:"account_name"`
}

func (q *Queries) ListRecurringTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListRecurringTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecurringTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringTransactionsByUserRow{}
	for rows.Next() {
		var i ListRecurringTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.Description,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.NextDueDate,
			&i.LastProcessedDate,
			&i.IsActive,
			&i.AutoCreate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNextDueDate = `-- name: UpdateNextDueDate :one
UPDATE recurring_transactions
SET next_due_date = $2,
    last_processed_date = CURRENT_DATE,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, account_id, category_id, type, amount, currency_code, description, frequency, start_date, end_date, next_due_date, last_processed_date, is_active, auto_create, created_at, updated_at
`

type UpdateNextDueDateParams struct {
	ID          pgtype.UUID `json:"id"`
	NextDueDate pgtype.Date `json:"next_due_date"`
}

func (q *Queries) UpdateNextDueDate(ctx context.Context, arg UpdateNextDueDateParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateNextDueDate, arg.ID, arg.NextDueDate)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.NextDueDate,
		&i.LastProcessedDate,
		&i.IsActive,
		&i.AutoCreate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringTransaction = `-- name: UpdateRecurringTransaction :one
UPDATE recurring_transactions
SET account_id = $2,
    category_id = $3,
    amount = $4,
    description = $5,
    frequency = $6,
    end_date = $7,
    auto_create = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $9
RETURNING id, user_id, account_id, category_id, type, amount, currency_code, description, frequency, start_date, end_date, next_due_date, last_processed_date, is_active, auto_create, created_at, updated_at
`

type UpdateRecurringTransactionParams struct {
	ID          pgtype.UUID    `json:"id"`
	AccountID   pgtype.UUID    `json:"account_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description string         `json:"description"`
	Frequency   string         `json:"frequency"`
	EndDate     pgtype.Date    `json:"end_date"`
	AutoCreate  *bool          `json:"auto_create"`
	UserID      pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateRecurringTransaction(ctx context.Context, arg UpdateRecurringTransactionParams) (RecurringTransaction, error) {
	row := q.db.QueryRow(ctx, updateRecurringTransaction,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Frequency,
		arg.EndDate,
		arg.AutoCreate,
		arg.UserID,
	)
	var i RecurringTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.Description,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.NextDueDate,
		&i.LastProcessedDate,
		&i.IsActive,
		&i.AutoCreate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
