// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    id, user_id, from_account_id, to_account_id,
    from_transaction_id, to_transaction_id, amount, to_amount, exchange_rate,
    transfer_date, description
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, from_account_id, to_account_id, from_transaction_id, to_transaction_id, amount, to_amount, exchange_rate, transfer_date, description, created_at
`

type CreateTransferParams struct {
	ID                pgtype.UUID    `json:"id"`
	UserID            pgtype.UUID    `json:"user_id"`
	FromAccountID     pgtype.UUID    `json:"from_account_id"`
	ToAccountID       pgtype.UUID    `json:"to_account_id"`
	FromTransactionID pgtype.UUID    `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID    `json:"to_transaction_id"`
	Amount            pgtype.Numeric `json:"amount"`
	ToAmount          pgtype.Numeric `json:"to_amount"`
	ExchangeRate      pgtype.Numeric `json:"exchange_rate"`
	TransferDate      pgtype.Date    `json:"transfer_date"`
	Description       *string        `json:"description"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.ID,
		arg.UserID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.FromTransactionID,
		arg.ToTransactionID,
		arg.Amount,
		arg.ToAmount,
		arg.ExchangeRate,
		arg.TransferDate,
		arg.Description,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.FromTransactionID,
		&i.ToTransactionID,
		&i.Amount,
		&i.ToAmount,
		&i.ExchangeRate,
		&i.TransferDate,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfers
WHERE id = $1 AND user_id = $2
`

type DeleteTransferParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransfer(ctx context.Context, arg DeleteTransferParams) error {
	_, err := q.db.Exec(ctx, deleteTransfer, arg.ID, arg.UserID)
	return err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT
    tr.id, tr.user_id, tr.from_account_id, tr.to_account_id, tr.from_transaction_id, tr.to_transaction_id, tr.amount, tr.to_amount, tr.exchange_rate, tr.transfer_date, tr.description, tr.created_at,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers tr
JOIN accounts fa ON tr.from_account_id = fa.id
JOIN accounts ta ON tr.to_account_id = ta.id
WHERE tr.id = $1 AND tr.user_id = $2
`

type GetTransferByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetTransferByIDRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	FromAccountID     pgtype.UUID      `json:"from_account_id"`
	ToAccountID       pgtype.UUID      `json:"to_account_id"`
	FromTransactionID pgtype.UUID      `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID      `json:"to_transaction_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	ToAmount          pgtype.Numeric   `json:"to_amount"`
	ExchangeRate      pgtype.Numeric   `json:"exchange_rate"`
	TransferDate      pgtype.Date      `json:"transfer_date"`
	Description       *string          `json:"description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	FromAccountName   string           `json:"from_account_name"`
	ToAccountName     string           `json:"to_account_name"`
}

func (q *Queries) GetTransferByID(ctx context.Context, arg GetTransferByIDParams) (GetTransferByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransferByID, arg.ID, arg.UserID)
	var i GetTransferByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.FromTransactionID,
		&i.ToTransactionID,
		&i.Amount,
		&i.ToAmount,
		&i.ExchangeRate,
		&i.TransferDate,
		&i.Description,
		&i.CreatedAt,
		&i.FromAccountName,
		&i.ToAccountName,
	)
	return i, err
}

const listTransfersByAccount = `-- name: ListTransfersByAccount :many
SELECT
    tr.id, tr.user_id, tr.from_account_id, tr.to_account_id, tr.from_transaction_id, tr.to_transaction_id, tr.amount, tr.to_amount, tr.exchange_rate, tr.transfer_date, tr.description, tr.created_at,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers tr
JOIN accounts fa ON tr.from_account_id = fa.id
JOIN accounts ta ON tr.to_account_id = ta.id
WHERE tr.user_id = $1
  AND (tr.from_account_id = $2 OR tr.to_account_id = $2)
ORDER BY tr.transfer_date DESC
LIMIT $3 OFFSET $4
`

type ListTransfersByAccountParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	FromAccountID pgtype.UUID `json:"from_account_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

type ListTransfersByAccountRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	FromAccountID     pgtype.UUID      `json:"from_account_id"`
	ToAccountID       pgtype.UUID      `json:"to_account_id"`
	FromTransactionID pgtype.UUID      `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID      `json:"to_transaction_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	ToAmount          pgtype.Numeric   `json:"to_amount"`
	ExchangeRate      pgtype.Numeric   `json:"exchange_rate"`
	TransferDate      pgtype.Date      `json:"transfer_date"`
	Description       *string          `json:"description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	FromAccountName   string           `json:"from_account_name"`
	ToAccountName     string           `json:"to_account_name"`
}

func (q *Queries) ListTransfersByAccount(ctx context.Context, arg ListTransfersByAccountParams) ([]ListTransfersByAccountRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByAccount,
		arg.UserID,
		arg.FromAccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersByAccountRow{}
	for rows.Next() {
		var i ListTransfersByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromTransactionID,
			&i.ToTransactionID,
			&i.Amount,
			&i.ToAmount,
			&i.ExchangeRate,
			&i.TransferDate,
			&i.Description,
			&i.CreatedAt,
			&i.FromAccountName,
			&i.ToAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByDateRange = `-- name: ListTransfersByDateRange :many
SELECT
    tr.id, tr.user_id, tr.from_account_id, tr.to_account_id, tr.from_transaction_id, tr.to_transaction_id, tr.amount, tr.to_amount, tr.exchange_rate, tr.transfer_date, tr.description, tr.created_at,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers tr
JOIN accounts fa ON tr.from_account_id = fa.id
JOIN accounts ta ON tr.to_account_id = ta.id
WHERE tr.user_id = $1
  AND tr.transfer_date BETWEEN $2 AND $3
ORDER BY tr.transfer_date DESC
`

type ListTransfersByDateRangeParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	TransferDate   pgtype.Date `json:"transfer_date"`
	TransferDate_2 pgtype.Date `json:"transfer_date_2"`
}

type ListTransfersByDateRangeRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	FromAccountID     pgtype.UUID      `json:"from_account_id"`
	ToAccountID       pgtype.UUID      `json:"to_account_id"`
	FromTransactionID pgtype.UUID      `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID      `json:"to_transaction_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	ToAmount          pgtype.Numeric   `json:"to_amount"`
	ExchangeRate      pgtype.Numeric   `json:"exchange_rate"`
	TransferDate      pgtype.Date      `json:"transfer_date"`
	Description       *string          `json:"description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	FromAccountName   string           `json:"from_account_name"`
	ToAccountName     string           `json:"to_account_name"`
}

func (q *Queries) ListTransfersByDateRange(ctx context.Context, arg ListTransfersByDateRangeParams) ([]ListTransfersByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByDateRange, arg.UserID, arg.TransferDate, arg.TransferDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersByDateRangeRow{}
	for rows.Next() {
		var i ListTransfersByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromTransactionID,
			&i.ToTransactionID,
			&i.Amount,
			&i.ToAmount,
			&i.ExchangeRate,
			&i.TransferDate,
			&i.Description,
			&i.CreatedAt,
			&i.FromAccountName,
			&i.ToAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByUser = `-- name: ListTransfersByUser :many
SELECT
    tr.id, tr.user_id, tr.from_account_id, tr.to_account_id, tr.from_transaction_id, tr.to_transaction_id, tr.amount, tr.to_amount, tr.exchange_rate, tr.transfer_date, tr.description, tr.created_at,
    fa.name AS from_account_name,
    ta.name AS to_account_name
FROM transfers tr
JOIN accounts fa ON tr.from_account_id = fa.id
JOIN accounts ta ON tr.to_account_id = ta.id
WHERE tr.user_id = $1
ORDER BY tr.transfer_date DESC, tr.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransfersByUserRow struct {
	ID                pgtype.UUID      `json:"id"`
	UserID            pgtype.UUID      `json:"user_id"`
	FromAccountID     pgtype.UUID      `json:"from_account_id"`
	ToAccountID       pgtype.UUID      `json:"to_account_id"`
	FromTransactionID pgtype.UUID      `json:"from_transaction_id"`
	ToTransactionID   pgtype.UUID      `json:"to_transaction_id"`
	Amount            pgtype.Numeric   `json:"amount"`
	ToAmount          pgtype.Numeric   `json:"to_amount"`
	ExchangeRate      pgtype.Numeric   `json:"exchange_rate"`
	TransferDate      pgtype.Date      `json:"transfer_date"`
	Description       *string          `json:"description"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	FromAccountName   string           `json:"from_account_name"`
	ToAccountName     string           `json:"to_account_name"`
}

func (q *Queries) ListTransfersByUser(ctx context.Context, arg ListTransfersByUserParams) ([]ListTransfersByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransfersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersByUserRow{}
	for rows.Next() {
		var i ListTransfersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.FromTransactionID,
			&i.ToTransactionID,
			&i.Amount,
			&i.ToAmount,
			&i.ExchangeRate,
			&i.TransferDate,
			&i.Description,
			&i.CreatedAt,
			&i.FromAccountName,
			&i.ToAccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
