// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactionsByUser = `-- name: CountTransactionsByUser :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
`

func (q *Queries) CountTransactionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, user_id, account_id, category_id, type,
    amount, currency_code, transaction_date, description, notes,
    payee, location, tags, is_recurring, recurring_transaction_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, user_id, account_id, category_id, type, amount, currency_code, transaction_date, description, notes, payee, location, tags, is_recurring, recurring_transaction_id, created_at, updated_at
`

type CreateTransactionParams struct {
	ID                     pgtype.UUID    `json:"id"`
	UserID                 pgtype.UUID    `json:"user_id"`
	AccountID              pgtype.UUID    `json:"account_id"`
	CategoryID             pgtype.UUID    `json:"category_id"`
	Type                   string         `json:"type"`
	Amount                 pgtype.Numeric `json:"amount"`
	CurrencyCode           string         `json:"currency_code"`
	TransactionDate        pgtype.Date    `json:"transaction_date"`
	Description            string         `json:"description"`
	Notes                  *string        `json:"notes"`
	Payee                  *string        `json:"payee"`
	Location               *string        `json:"location"`
	Tags                   []string       `json:"tags"`
	IsRecurring            *bool          `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID    `json:"recurring_transaction_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.CurrencyCode,
		arg.TransactionDate,
		arg.Description,
		arg.Notes,
		arg.Payee,
		arg.Location,
		arg.Tags,
		arg.IsRecurring,
		arg.RecurringTransactionID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.TransactionDate,
		&i.Description,
		&i.Notes,
		&i.Payee,
		&i.Location,
		&i.Tags,
		&i.IsRecurring,
		&i.RecurringTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getIncomeVsExpenseByMonth = `-- name: GetIncomeVsExpenseByMonth :many
SELECT
    DATE_TRUNC('month', transaction_date) AS month,
    SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END) AS total_income,
    SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END) AS total_expense
FROM transactions
WHERE user_id = $1
  AND transaction_date BETWEEN $2 AND $3
GROUP BY DATE_TRUNC('month', transaction_date)
ORDER BY month
`

type GetIncomeVsExpenseByMonthParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetIncomeVsExpenseByMonthRow struct {
	Month        pgtype.Interval `json:"month"`
	TotalIncome  int64           `json:"total_income"`
	TotalExpense int64           `json:"total_expense"`
}

func (q *Queries) GetIncomeVsExpenseByMonth(ctx context.Context, arg GetIncomeVsExpenseByMonthParams) ([]GetIncomeVsExpenseByMonthRow, error) {
	rows, err := q.db.Query(ctx, getIncomeVsExpenseByMonth, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIncomeVsExpenseByMonthRow{}
	for rows.Next() {
		var i GetIncomeVsExpenseByMonthRow
		if err := rows.Scan(&i.Month, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySpendingByCategory = `-- name: GetMonthlySpendingByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.color,
    c.icon,
    SUM(t.amount) AS total_amount,
    COUNT(t.id) AS transaction_count
FROM transactions t
JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND t.type = 'expense'
  AND DATE_TRUNC('month', t.transaction_date) = DATE_TRUNC('month', $2::DATE)
GROUP BY c.id, c.name, c.color, c.icon
ORDER BY total_amount DESC
`

type GetMonthlySpendingByCategoryParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

type GetMonthlySpendingByCategoryRow struct {
	CategoryID       pgtype.UUID `json:"category_id"`
	CategoryName     string      `json:"category_name"`
	Color            *string     `json:"color"`
	Icon             *string     `json:"icon"`
	TotalAmount      int64       `json:"total_amount"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetMonthlySpendingByCategory(ctx context.Context, arg GetMonthlySpendingByCategoryParams) ([]GetMonthlySpendingByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySpendingByCategory, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySpendingByCategoryRow{}
	for rows.Next() {
		var i GetMonthlySpendingByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.Color,
			&i.Icon,
			&i.TotalAmount,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name, a.name AS account_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.id = $1 AND t.user_id = $2
`

type GetTransactionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetTransactionByIDRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.TransactionDate,
		&i.Description,
		&i.Notes,
		&i.Payee,
		&i.Location,
		&i.Tags,
		&i.IsRecurring,
		&i.RecurringTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.AccountName,
	)
	return i, err
}

const getTransactionSummaryByDateRange = `-- name: GetTransactionSummaryByDateRange :one
SELECT
    COUNT(*) AS transaction_count,
    SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END) AS total_income,
    SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END) AS total_expense
FROM transactions
WHERE user_id = $1
  AND transaction_date BETWEEN $2 AND $3
`

type GetTransactionSummaryByDateRangeParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

type GetTransactionSummaryByDateRangeRow struct {
	TransactionCount int64 `json:"transaction_count"`
	TotalIncome      int64 `json:"total_income"`
	TotalExpense     int64 `json:"total_expense"`
}

func (q *Queries) GetTransactionSummaryByDateRange(ctx context.Context, arg GetTransactionSummaryByDateRangeParams) (GetTransactionSummaryByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getTransactionSummaryByDateRange, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	var i GetTransactionSummaryByDateRangeRow
	err := row.Scan(&i.TransactionCount, &i.TotalIncome, &i.TotalExpense)
	return i, err
}

const listTransactionsByAccount = `-- name: ListTransactionsByAccount :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1 AND t.account_id = $2
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByAccountParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListTransactionsByAccountRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
}

func (q *Queries) ListTransactionsByAccount(ctx context.Context, arg ListTransactionsByAccountParams) ([]ListTransactionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccount,
		arg.UserID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByAccountRow{}
	for rows.Next() {
		var i ListTransactionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCategory = `-- name: ListTransactionsByCategory :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, a.name AS account_name
FROM transactions t
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.user_id = $1 AND t.category_id = $2
ORDER BY t.transaction_date DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByCategoryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type ListTransactionsByCategoryRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) ListTransactionsByCategory(ctx context.Context, arg ListTransactionsByCategoryParams) ([]ListTransactionsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByCategory,
		arg.UserID,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByCategoryRow{}
	for rows.Next() {
		var i ListTransactionsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name, a.name AS account_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.user_id = $1
  AND t.transaction_date BETWEEN $2 AND $3
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $4 OFFSET $5
`

type ListTransactionsByDateRangeParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
	Limit             int32       `json:"limit"`
	Offset            int32       `json:"offset"`
}

type ListTransactionsByDateRangeRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]ListTransactionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange,
		arg.UserID,
		arg.TransactionDate,
		arg.TransactionDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByDateRangeRow{}
	for rows.Next() {
		var i ListTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByTag = `-- name: ListTransactionsByTag :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name, a.name AS account_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.user_id = $1 AND $2 = ANY(t.tags)
ORDER BY t.transaction_date DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByTagParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Tags   []string    `json:"tags"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsByTagRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) ListTransactionsByTag(ctx context.Context, arg ListTransactionsByTagParams) ([]ListTransactionsByTagRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByTag,
		arg.UserID,
		arg.Tags,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByTagRow{}
	for rows.Next() {
		var i ListTransactionsByTagRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByType = `-- name: ListTransactionsByType :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name, a.name AS account_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.user_id = $1 AND t.type = $2
ORDER BY t.transaction_date DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsByTypeRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) ListTransactionsByType(ctx context.Context, arg ListTransactionsByTypeParams) ([]ListTransactionsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByType,
		arg.UserID,
		arg.Type,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByTypeRow{}
	for rows.Next() {
		var i ListTransactionsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT t.id, t.user_id, t.account_id, t.category_id, t.type, t.amount, t.currency_code, t.transaction_date, t.description, t.notes, t.payee, t.location, t.tags, t.is_recurring, t.recurring_transaction_id, t.created_at, t.updated_at, c.name AS category_name, a.name AS account_name
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
LEFT JOIN accounts a ON t.account_id = a.id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListTransactionsByUserRow struct {
	ID                     pgtype.UUID      `json:"id"`
	UserID                 pgtype.UUID      `json:"user_id"`
	AccountID              pgtype.UUID      `json:"account_id"`
	CategoryID             pgtype.UUID      `json:"category_id"`
	Type                   string           `json:"type"`
	Amount                 pgtype.Numeric   `json:"amount"`
	CurrencyCode           string           `json:"currency_code"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	Description            string           `json:"description"`
	Notes                  *string          `json:"notes"`
	Payee                  *string          `json:"payee"`
	Location               *string          `json:"location"`
	Tags                   []string         `json:"tags"`
	IsRecurring            *bool            `json:"is_recurring"`
	RecurringTransactionID pgtype.UUID      `json:"recurring_transaction_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	CategoryName           *string          `json:"category_name"`
	AccountName            *string          `json:"account_name"`
}

func (q *Queries) ListTransactionsByUser(ctx context.Context, arg ListTransactionsByUserParams) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByUserRow{}
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.CurrencyCode,
			&i.TransactionDate,
			&i.Description,
			&i.Notes,
			&i.Payee,
			&i.Location,
			&i.Tags,
			&i.IsRecurring,
			&i.RecurringTransactionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $2,
    amount = $3,
    transaction_date = $4,
    description = $5,
    notes = $6,
    payee = $7,
    location = $8,
    tags = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $10
RETURNING id, user_id, account_id, category_id, type, amount, currency_code, transaction_date, description, notes, payee, location, tags, is_recurring, recurring_transaction_id, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID    `json:"id"`
	CategoryID      pgtype.UUID    `json:"category_id"`
	Amount          pgtype.Numeric `json:"amount"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
	Description     string         `json:"description"`
	Notes           *string        `json:"notes"`
	Payee           *string        `json:"payee"`
	Location        *string        `json:"location"`
	Tags            []string       `json:"tags"`
	UserID          pgtype.UUID    `json:"user_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.TransactionDate,
		arg.Description,
		arg.Notes,
		arg.Payee,
		arg.Location,
		arg.Tags,
		arg.UserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.CurrencyCode,
		&i.TransactionDate,
		&i.Description,
		&i.Notes,
		&i.Payee,
		&i.Location,
		&i.Tags,
		&i.IsRecurring,
		&i.RecurringTransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
