// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUser = `-- name: CountUser :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, firebase_uid, currency_code)
VALUES ($1, $2, $3)
RETURNING id, firebase_uid, currency_code, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	FirebaseUid  string      `json:"firebase_uid"`
	CurrencyCode string      `json:"currency_code"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.FirebaseUid, arg.CurrencyCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CurrencyCode,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, currency_code, is_admin, created_at, updated_at FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CurrencyCode,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, currency_code, is_admin, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.CurrencyCode,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, firebase_uid, currency_code, is_admin, created_at, updated_at FROM users
`

func (q *Queries) ListUser(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.CurrencyCode,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users
SET is_admin = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetUserAdminParams struct {
	ID      pgtype.UUID `json:"id"`
	IsAdmin bool        `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const updateUserCurrency = `-- name: UpdateUserCurrency :exec
UPDATE users
SET currency_code = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserCurrencyParams struct {
	ID           pgtype.UUID `json:"id"`
	CurrencyCode string      `json:"currency_code"`
}

func (q *Queries) UpdateUserCurrency(ctx context.Context, arg UpdateUserCurrencyParams) error {
	_, err := q.db.Exec(ctx, updateUserCurrency, arg.ID, arg.CurrencyCode)
	return err
}
